server {
    listen 8080;
    server_name localhost;

    location / {
        allow_methods GET;
        root ./www;
        index index.html;
        cgi .bla ./cgi_tester;

    }

    location /post_body/ {
        allow_methods POST;
        root ./www;
        client_max_body_size 100;
    }

    location /directory/ {
        allow_methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
		cgi .bla ./cgi_tester;

    }

    location /cgi-bin/ {
        allow_methods GET POST;
        root ./www/cgi-bin;
        cgi .bla ./cgi_tester;
    }
    location .bla {
		allow_methods POST;

		cgi .bla ./cgi_tester;
	}

}